name: django-environment
channels:
  - anaconda
  - defaults
dependencies:
  - python=3.13
  - django
  - sqlite
  - pip
  - pip:
    - crispy-bootstrap5
    - django-environ
    - djangorestframework
    - gunicorn
    - numpy
    - python-decouple
    - python-dotenv
    - whitenoise
