#! /bin/sh

# colors
# black="#000000"
blue="#007FFF"
# rust="#A73200"
# electric_green="#32FF00"
white="#FFFFFF"

pgrep -x sxhkd >/dev/null || sxhkd &
"$HOME/.config/polybar/launch.sh"

bspc monitor DP2 -d 1 2 3 4 5
bspc monitor DP1 -d 6 7 8 9 10

##--Global Settings--##
bspc config focused_border_color "$blue"
bspc config normal_border_color "$white"
bspc config active_border_color "$white"

##--Monitor and Desktop Settings--##
bspc config top_padding 44
bspc config bottom_padding 4
bspc config left_padding 4
bspc config right_padding 4
bspc config border_width 1
bspc config window_gap 4
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config single_monocle false

bspc rule -a Brave-browser desktop=^1
bspc rule -a TIPP10 desktop=^2
bspc rule -a bottles desktop=^2
bspc rule -a Upwork desktop=^2
bspc rule -a draw.io desktop=^3
bspc rule -a Gimp desktop=^3
bspc rule -a Thunar desktop=^3
