#! /bin/sh

# colors
blue="#0066b2"
white="#FFFFFF"
# black="#000000"

pgrep -x sxhkd >/dev/null || sxhkd &
"$HOME/.config/polybar/launch.sh"

bspc monitor DP2 -d 1 2 3 4
bspc monitor DP1 -d 5 6 7 8
bspc monitor eDP1 -d 9

##--Global Settings--##
bspc config focused_border_color "$blue"
bspc config normal_border_color "$white"
bspc config active_border_color "$white"

##--Monitor and Desktop Settings--##
bspc config top_padding 40
bspc config bottom_padding 10
bspc config left_padding 2
bspc config right_padding 2
bspc config border_width 2
bspc config window_gap 2
bspc config split_ratio 0.50
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config focus_follows_pointer true
bspc config single_monocle false

bspc rule -a Brave-browser desktop=^1
bspc rule -a VSCodium desktop=^5
bspc rule -a obsidian desktop=^6
bspc rule -a Spotify desktop=^7
