[global/wm]
include-file = ~/.config/polybar/colors.ini
include-file = ~/.config/polybar/modules.ini

[settings]
format-padding = 0.5
format-margin = 0.0
screenchange-reload = true

[bar/eric-1]
width = 99.20%
height = 33
offset-x = 0.45%
offset-y = 0.20%
fixed-center = true
bottom = false
monitor = DP1
background = ${colors.black}
foreground = ${colors.deepskyblue}
line-size = 2
line-colour = ${colors.deepskyblue}
border-size = 0
border-color = ${colors.deepskyblue}
padding-left = 0
padding-right = 2
module-margin-left = 0
module-margin-right = 3

font-0 = "Roboto:style=Medium:size=12;2"
font-1 = "JetBrainsMono Nerd Font Mono:style=Regular:pixelsize=21;3"

modules-left = bspwm
modules-right = filesystem date time volume

wm-restack = bspwm

[bar/eric-2]
width = 99.20%
height = 33
offset-x = 0.45%
offset-y = 0.20%
fixed-center = true
bottom = false
monitor = DP2
background = ${colors.black}
foreground = ${colors.deepskyblue}
line-size = 2
line-colour = ${colors.deepskyblue}
border-size = 0
border-color = ${colors.deepskyblue}
padding-left = 0
padding-right = 2
module-margin-left = 0
module-margin-right = 3

font-0 = "Roboto:style=Medium:size=12;2"
font-1 = "JetBrainsMono Nerd Font Mono:style=Regular:pixelsize=21;3"
font-2 = "Font Awesome 6 Free:style=Regular:pixelsize=10;1"
font-3 = "Font Awesome 6 Free:style=Solid:pixelsize=10;1"
font-4 = "Font Awesome 6 Brands:pixelsize=10;1"

modules-left = bspwm
modules-right = pacman-updates pacman-packages filesystem date time volume tray

wm-restack = bspwm

; vim:ft=dosini
