[global/wm]
include-file = ~/.config/polybar/colors.ini
include-file = ~/.config/polybar/modules.ini

[settings]
format-padding = 0.5
format-margin = 0.0
screenchange-reload = true

[bar/eric-1]
width = 99.20%
height = 33
offset-x = 0.45%
offset-y = 0.20%
fixed-center = true
bottom = false
monitor = DP1
background = ${colors.black}
foreground = ${colors.cyan}
line-size = 3
line-colour = ${colors.cyan}
border-size = 1
border-color = ${colors.cyan}
padding-left = 0
padding-right = 1
module-margin-left = 0
module-margin-right = 1

font-0 = JetBrainsMono Nerd Font:style=Medium:pixelsize=12;4
font-1 = JetBrainsMono Nerd Font Mono:style=Medium:pixelsize=20;4

modules-left = bspwm

; separator = 
; separator-foreground = ${colors.cyan}
; separator-padding = 1

wm-restack = bspwm

[bar/eric-2]
width = 99.20%
height = 33
offset-x = 0.45%
offset-y = 0.20%
fixed-center = true
bottom = false
monitor = DP2
background = ${colors.black}
foreground = ${colors.cyan}
line-size = 2
line-colour = ${colors.cyan}
border-size = 1
border-color = ${colors.cyan}
padding-left = 0
padding-right = 1
module-margin-left = 0
module-margin-right = 1

font-0 = JetBrainsMono Nerd Font:style=Medium:pixelsize=12;4
font-1 = JetBrainsMono Nerd Font Mono:style=Medium:pixelsize=20;4

modules-left = bspwm
modules-right = pacman-packages filesystem date time volume

tray-detached = false
tray-offset-x = 0
tray-offset-y = 0
tray-position = right
tray-padding = 4
tray-maxsize = 20
tray-scale = 1.0
tray-background = ${colors.black}

wm-restack = bspwm

; vim:ft=dosini
