[module/tray]
type = internal/tray
tray-background = ${colors.black}
format-margin = 1px
tray-spacing = 1px
tray-size = 30

[module/pacman-updates]
type = custom/script
exec = checkupdates | wc -l
interval = 3600
label = Updates: %output%
format-prefix = " "
format-foreground = ${colors.deepskyblue}
format-background = ${colors.black}
format-prefix-foreground = ${colors.deepskyblue}
format-underline = ${colors.deepskyblue}

[module/pacman-packages]
type = custom/script
exec = pacman -Q | wc -l
interval = 300
label= " Installed: %output%"
format-prefix = "󰏖 "
format-foreground = ${colors.deepskyblue}
format-background = ${colors.black}
format-prefix-foreground = ${colors.deepskyblue}
format-underline = ${colors.deepskyblue}

[module/filesystem]
type = internal/fs
mount-0 = /
mount-1 = /home
mount-2 = /storage
interval = 60
fixed-values = true
spacing = 2
; format-mounted = 󰋊 <label-mounted>
format-mounted =  <label-mounted>
format-mounted-foreground = ${colors.chartreuse}
; label-mounted = %free% of %total%
label-mounted = %free%
label-mounted-foreground = ${colors.chartreuse}
label-mounted-underline = ${colors.chartreuse}
format-mounted-underline = ${colors.chartreuse}

[module/date]
type = custom/script 
exec = date "+%a, %b %d, %Y"
interval = 3600
label = "%output%"
format-prefix = " "
format-foreground = ${colors.deepskyblue}
format-background = ${colors.black}
format-prefix-foreground = ${colors.deepskyblue}
format-prefix-underline = ${colors.deepskyblue}
label-underline = ${colors.deepskyblue}

[module/time]
type = custom/script 
; exec = date "+%I:%M:%S %p"
exec = date "+%H:%M %p"
interval = 1
label = "%output%"
format-prefix = " "
format-foreground = ${colors.deepskyblue}
format-background = ${colors.black}
format-prefix-foreground = ${colors.deepskyblue}
label-underline = ${colors.deepskyblue}
format-prefix-underline = ${colors.deepskyblue}

[module/bspwm]
type = internal/bspwm
pin-workspaces = true
enable-scroll = true
label-focused = %icon%
label-focused-background = ${colors.black}
label-focused-foreground = ${colors.deepskyblue}
label-focused-underline = ${colors.deepskyblue}
label-focused-padding = 2
label-occupied = %icon%
label-occupied-padding = 2
label-occupied-foreground = ${colors.gold}
label-empty = %icon%
label-empty-foreground = ${colors.white}
label-empty-padding = 2
scroll-up = bspwm-desknext
scroll-down = bspwm-deskprev

ws-icon-0 = 1;󰼏 
ws-icon-1 = 2;󰼐
ws-icon-2 = 3;󰼑
ws-icon-3 = 4;󰼒
ws-icon-4 = 5;󰼓
ws-icon-5 = 6;󰼔
ws-icon-6 = 7;󰼕
ws-icon-7 = 8;󰼖
ws-icon-8 = 9;󰼗

[module/volume]
type = internal/pulseaudio

master-soundcard = default
speaker-soundcard = default 
headphone-soundcard = default 

format-volume = <ramp-volume>  <label-volume>
format-muted = <label-muted>
label-volume = %percentage%
ramp-volume-foreground = ${colors.gold}
label-volume-foreground = ${colors.gold}
label-muted = 
label-muted-foreground = ${colors.red}
format-volume-underline = ${colors.gold}
format-muted-underline = ${colors.red}

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 

[module/task-active]
type = custom/script
exec = ~/.config/polybar/scripts/task_active.sh
interval = 60
format = <label>
label = %output%
format-foreground = ${colors.tomato}
format-background = ${colors.black}
format-prefix-underline = ${colors.tomato}
format-underline = ${colors.tomato}
