#-------------------------------------------------------------------------
# Profiles
#-------------------------------------------------------------------------
save-position-on-quit=yes
fullscreen=yes

#-------------------------------------------------------------------------
# Video Settings
# ------------------------------------------------------------------------
cache=yes
vo=gpu
gpu-api=opengl
demuxer-max-bytes=256MiB
demuxer-cache-wait=yes

#-------------------------------------------------------------------------
# OSD Configuration
# ------------------------------------------------------------------------
osd-font="Roboto"
osd-font-size=14

#-------------------------------------------------------------------------
# Audio Configuration
# ------------------------------------------------------------------------
volume=70
volume-max=200
ao=pulse
pulse-latency-hacks=yes

#-------------------------------------------------------------------------
# Subtitles
#-------------------------------------------------------------------------
sub-font="Roboto"
sub-font-size=30

#-------------------------------------------------------------------------
# Screenshots
#-------------------------------------------------------------------------
screenshot-directory="/storage/Pictures/screenshots/"
screenshot-template="%F %02n %p"
